---
name: Publish to PyPI

on:
  push:
    tags:
      - 'v*.*.*'   # e.g. v1.2.3

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.x'
      - name: Install build tools
        run: pip install build tomli
      - name: Verify tag matches pyproject.toml version
        run: |
          TAG="${GITHUB_REF#refs/tags/v}"
          FILE_VER=$(python -c "import tomli;print(tomli.load(open('pyproject.toml'))['project']['version'])")
          [ "$TAG" = "$FILE_VER" ] || { echo "Tag $TAG != pyproject $FILE_VER"; exit 1; }
      - name: Build dists
        run: python -m build
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: dist
          path: dist/*

  publish:
    needs: build
    runs-on: ubuntu-latest
    environment: pypi
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: dist
          path: dist
      - name: Publish to PyPI via OIDC
        uses: pypa/gh-action-pypi-publish@release/v1
